# Generated by Django 2.2.5 on 2022-03-25 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Locition',
            new_name='Location',
        ),
    ]
