# Generated by Django 2.2.5 on 2022-03-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0005_auto_20220325_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost',
            name='link',
            field=models.IntegerField(max_length=11, verbose_name='失主联系方式/(QQ/微信)'),
        ),
    ]
