# Generated by Django 2.2.5 on 2022-03-26 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0008_found'),
    ]

    operations = [
        migrations.RenameField(
            model_name='found',
            old_name='lost_time',
            new_name='found_time',
        ),
    ]
