# Generated by Django 2.2.5 on 2022-03-26 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0010_foundrecor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foundrecor',
            new_name='FoundRecord',
        ),
    ]
