# Generated by Django 2.2.5 on 2022-03-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0013_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='found',
            name='username',
            field=models.CharField(default='null', max_length=32, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='foundrecord',
            name='username',
            field=models.CharField(default='null', max_length=32, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='lost',
            name='username',
            field=models.CharField(default='null', max_length=32, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='lostrecord',
            name='username',
            field=models.CharField(default='null', max_length=32, verbose_name='用户名'),
        ),
    ]
